const data = [
  {
    "type":"multiple",
    "difficulty":"medium",
    "category":"Entertainment: Comics",
    "question":"Who was the inspiration for Cuthbert Calculus in the Tintin series?",
    "correct_answer":"Auguste Picard",
    "incorrect_answers":["Jacques Piccard","Will Morris","J. Cecil Maby"]
  },{"type":"multiple","difficulty":"hard","category":"Entertainment: Japanese Anime &amp; Manga","question":"In what year did the manga &quot;Ping Pong&quot; begin serialization?","correct_answer":"1996","incorrect_answers":["2014","2010","2003"]},{"type":"multiple","difficulty":"medium","category":"Celebrities","question":"When was Elvis Presley born?","correct_answer":"January 8, 1935","incorrect_answers":["December 13, 1931","July 18, 1940","April 17, 1938"]},{"type":"boolean","difficulty":"easy","category":"General Knowledge","question":"It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.","correct_answer":"False","incorrect_answers":["True"]},{"type":"multiple","difficulty":"medium","category":"Entertainment: Music","question":"Who performed the guitar solo on Michael Jackson&#039;s hit &quot;Beat It&quot;?","correct_answer":"Eddie Van Halen","incorrect_answers":["Steve Vai","Kirk Hammett","Zakk Wylde"]},{"type":"boolean","difficulty":"medium","category":"Entertainment: Japanese Anime &amp; Manga","question":"The animated film &quot;Spirited Away&quot; won the Academy Award for Best Animated Feature at the 75th Academy Awards in 2003.","correct_answer":"True","incorrect_answers":["False"]},{"type":"boolean","difficulty":"easy","category":"Science: Computers","question":"The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.","correct_answer":"False","incorrect_answers":["True"]},{"type":"multiple","difficulty":"medium","category":"History","question":"Which historical conflict killed the most people?","correct_answer":"World War II","incorrect_answers":["Taiping Rebellion","Three Kingdoms War","Mongol conquests"]},{"type":"multiple","difficulty":"hard","category":"Entertainment: Musicals &amp; Theatres","question":"After England, more Shakespeare plays are set in this present day country than in any other.","correct_answer":"Italy","incorrect_answers":["United States","Greece","France"]},{"type":"multiple","difficulty":"medium","category":"Animals","question":"What type of animal is a natterjack?","correct_answer":"Toad","incorrect_answers":["Bird","Fish","Insect"]}
]

export default data;